Use conda-forge for Python packages
This will hopefully work around the conflict that is occurring on travis
ci when setting up the Python 3.4 environment.

Specifically:
    $ conda install -y python=$TRAVIS_PYTHON_VERSION
    Fetching package metadata ...........
    Solving package specifications: .
    UnsatisfiableError: The following specifications were found to be in
    conflict:
      - pysocks -> python 2.7*
      - python 3.4*
    Use "conda info <package>" to see the dependencies for each package.

Using conda-forge on my macbook doesn't reproduce this problem.