Garbage collect during teardown so tests run on Windows
On Windows files can't be removed while still open.
The time between the db object going out of scope and tear down
occurring is too short for garbage collection to have run.
As a result SQLAlchemy has not released the sqlite file by the
time tear down occurs.
This results in an error on Windows:
    PermissionError: [WinError 32] The process cannot access the file
    because it is being used by another process:
Therefore garbage collect before trying to remove temporary files.

Signed-off-by: Andrew MacDonald <andrew@maccas.net>